### ISSUE TITLE
Double time conversion issue on DST day

### ISSUE THREAD

**Issue by echipachenko** [enioka-Haute-Couture/jqm#488]
Hi guys,
We've faced with a really strange issue on March 12th and March 13th.

March 13th - is a DST day in the EST timezone, so on March 13, we don't have a time from 02:00 till 03:00, as after 01:59 it goes to 03:00 (time change https://www.timeanddate.com/time/change/canada).

All jobs submitted on March 12th from 21:00 till 22:00 were failed, because of the following error:

```[2022-03-12 21:02:25.274] [ERROR] [#812494604/105/] [71] [@] [jqmjobs] [] [LoggingContextSupport] [DIMEMT] [] : Uncatched exception 
java.sql.SQLException: Incorrect datetime value: '2022-03-13 02:02:25.261000' for column `frontier_jobmanagement`.`job_instance`.`DATE_ENQUEUE` at row 1
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1694)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1556)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1519)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
	... 52 common frames omitted
Wrapped by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Incorrect datetime value: '2022-03-13 02:02:25.261000' for column `frontier_jobmanagement`.`job_instance`.`DATE_ENQUEUE` at row 1
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 51 common frames omitted
Wrapped by: java.sql.SQLSyntaxErrorException: (conn=121848) Incorrect datetime value: '2022-03-13 02:02:25.261000' for column `frontier_jobmanagement`.`job_instance`.`DATE_ENQUEUE` at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:266)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181)
	at com.enioka.jqm.jdbc.DbConn.runUpdate(DbConn.java:108) [5 skipped]
	at com.enioka.jqm.model.JobInstance.enqueue(JobInstance.java:570)
	at com.enioka.jqm.api.JdbcClient.enqueueWithCnx(JdbcClient.java:348)
	at com.enioka.jqm.api.JdbcClient.enqueue(JdbcClient.java:197)
	at com.frontier.job.service.JobSubmitService.submit(JobSubmitService.java:58)
	at com.frontier.job.service.impl.JobServiceImpl.submit(JobServiceImpl.java:47)
	... 43 common frames omitted
Wrapped by: com.enioka.jqm.jdbc.DatabaseException: INSERT INTO JOB_INSTANCE (ID, DATE_ENQUEUE, EMAIL, APPLICATION, KEYWORD1, KEYWORD2, KEYWORD3, MODULE, INTERNAL_POSITION, PARENT, PROGRESS, SESSION_KEY, STATUS, USERNAME, JOBDEF, QUEUE, HIGHLANDER, FROM_SCHEDULE, DATE_NOT_BEFORE, PRIORITY, INSTRUCTION) VALUES(?, UTC_TIMESTAMP(3), ?, ?, ?, ?, ?, ?, ROUND(UNIX_TIMESTAMP(NOW(4)) * 1000), ?, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	at com.enioka.jqm.jdbc.DbConn.runUpdate(DbConn.java:129)
	at com.enioka.jqm.model.JobInstance.enqueue(JobInstance.java:570)
	at com.enioka.jqm.api.JdbcClient.enqueueWithCnx(JdbcClient.java:348)
	... 41 common frames omitted
```

It seems like JQM convert EST timestamp to UTC (found that logic in the JQM DbConn class) for all Calendar instances, and in our case, job submission time 21:02:25 EST was converted to 02:02:25 UTC and it goes to the DB.
But the DB is in the EST timezone, so DB thought that the timestamp come in the EST timezone and the DB rejected the time, as in EST we don't have 02:02:25 on March 13th because of the DST time change.  Also, MariaDB saves ALL TIMESTAMP values in the UTC zone regardless of server timezone, do the DB also do timezone conversion.

Can you please make the line ```private static Calendar utcZone = Calendar.getInstance(TimeZone.getTimeZone("UTC"));``` in class DbConn configurable? Or maybe you can provide more accurate solution?
Firstly, I thought that this was a MariaDB bug, and I've reported a ticket for the MariaDB https://jira.mariadb.org/browse/MDEV-28046 but actually, it seems to be a JQM bug.
Thank you.

**Comment by echipachenko** [comment]
Hi @marcanpilami,
do you have any updated on this ticket?

**Comment by echipachenko** [comment]
Seems that it's a mariadb bug.
Steps:
1. CHANGE SYSTEM DATE:
`sudo date -s "12 MAR 2022 21:01:00"`
2. Run Query:
```
CREATE TABLE `utc_timestamp_bug` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `timest` timestamp(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

select now(), UTC_TIMESTAMP(3), IF(@@session.time_zone = 'SYSTEM', @@system_time_zone, @@session.time_zone)

insert into utc_timestamp_bug values (1,  UTC_TIMESTAMP(3))
```
